spring:
  datasource:
    url: jdbc:mysql://database-1.cxlfc35byayt.ap-northeast-2.rds.amazonaws.com:3306/mall_db
    username: admin
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver