spring:
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB

  profiles:
    active: dev

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace