spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mall_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true
#
#  sql:
#    init:
#      mode: always
